### PR TITLE
added new towns

### PR DESCRIPTION
**Pull request by 4eug**

### CODE REVIEW

**Review by oliverboamah — CHANGES_REQUESTED** [review]
Thanks for additions to the northern region.

Please review your submission to ensure that the towns are in alphabetical order and push again.

**Comment by 4eug** [comment]
Changes made
Please accept request

**Review by oliverboamah — CHANGES_REQUESTED** [review]
Tamale should come before Tatale, please check.

Thank for the quick response.

**Comment by 4eug** [comment]
Done Please check

**Review by oliverboamah — APPROVED** [review]
Great. Thanks for your submission.

**Comment by 4eug** [comment]
You are welcome.

**Review by oliverboamah — APPROVED** [review]
Great. Thanks for your submission.

**Pull request merged**
